# GitLab CI configuration file

image: registry.gitlab.com/cki-project/experimental/containers/builder-fedora30

stages:
  - test

variables:
  GIT_DEPTH: "5"

test_rh_configs:
  stage: test
  script: make rh-configs

# This job exports the packaging-related scripts and files for use with other
# upstream kernel trees.
redhat_export:
  stage: test
  script:
    - git log -1 --pretty=format:%H
  only:
    refs:
      - internal
  artifacts:
    when: always
    paths:
      - makefile
      - Makefile.rhelver
      - redhat/
