# GitLab CI configuration file

image: registry.gitlab.com/cki-project/experimental/containers/builder-fedora30

stages:
  - test

variables:
  GIT_DEPTH: "5"

test_rh_configs:
  stage: test
  script: make rh-configs
  only:
    refs:
      - merge_requests
      - internal

# This job exports the packaging-related scripts and files for use with other
# upstream kernel trees.
redhat_export:
  stage: test
  script:
    - git log -1 --pretty=format:%H
  only:
    refs:
      - internal
  artifacts:
    when: always
    paths:
      - makefile
      - Makefile.rhelver
      - redhat/

# Bring some commits from a make rh-release back to internal
update_internal:
   stage: test
   before_script:
     - echo "fastestmirror=true" >> /etc/dnf/dnf.conf
     - dnf -y install dnf-utils git openssh-clients tar
     - eval $(ssh-agent -s)
     - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
     - mkdir -p ~/.ssh
     - chmod 700 ~/.ssh
   script:
     - redhat/update-internal.sh $GIT_DEPTH
   only:
     - master
