/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Header that contains the code (mostly headers) for which Rust bindings
 * will be automatically generated by `bindgen`.
 *
 * Sorted alphabetically.
 */

#include <linux/errname.h>
#include <linux/slab.h>
#include <linux/ktime.h>
#include <linux/lockdep.h>
#include <linux/refcount.h>
#include <linux/wait.h>
#include <linux/siphash.h>
#include <linux/sched.h>
#include <linux/timekeeping.h>

/* `bindgen` gets confused at certain things. */
const size_t BINDINGS_ARCH_SLAB_MINALIGN = ARCH_SLAB_MINALIGN;
const gfp_t BINDINGS_GFP_KERNEL = GFP_KERNEL;
const gfp_t BINDINGS___GFP_ZERO = __GFP_ZERO;
