# variables that can be overrided by ~/.rhpkg.mk or $(TOPDIR)/.rhpkg.mk
#

# load configuration, starting with home directory then local
ifeq ("$(RHDISTGIT_CACHE)", "")
 ifneq ("$(wildcard ${HOME}/.rhpkg.mk)", "")
  include ${HOME}/.rhpkg.mk
 endif
 ifneq ("$(wildcard $(TOPDIR)/.rhpkg.mk)", "")
  include $(TOPDIR)/.rhpkg.mk
 endif
endif
